application:
  port: 5000

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "ticketing_system"

auth:
  access_token_lifetime: 15m
  refresh_token_lifetime: 30d
  private_key_path: ./keys/private.pem
  public_key_path: ./keys/public.pem
  issuer: ticketing-system
  
redis:
  url: "redis://localhost:6379"

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000