FROM node:24-alpine as builder

WORKDIR /app

COPY www/package*.json ./

RUN npm install

COPY www .

RUN npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/build /usr/share/nginx/html

COPY ./infra/nginx-prod.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]